export { default as Header } from './Header'
export { default as Content } from './Content'
export { default as Sidebar } from './Sidebar'
export { default as ProductsTable } from './ProductsTable'
export { default as AddProduct } from './AddProduct'
export { default as Modal } from './Modal'
